### ISSUE TITLE
'area' not a global parameter

### ISSUE THREAD

**Issue by vansjyo** [xiongsiting/SHARAD3d#1]
https://github.com/xiongsiting/SHARAD3d/blob/4220a4860c721511b78ba99cb796b02e86cee457/SHARAD/SHARAD2d.py#L91-L96

I was using this code to test something when I saw the variable `area`, which I'm not sure is being rightly placed. I was wondering if you intended to refer the variable `roifile` instead.
Would be great if you could correct me if I'm wrong, or else I would be glad to open a PR if you wish.

**Comment by xiongsiting** [comment]
Yes, you are right. The area should be changed to 'roifile'.
